### PR TITLE
Added UberLoggerAppWindow.ToggleWindow.

### PR DESCRIPTION
**Pull request by ewanmellor**
This allows the window to be toggled programmatically.

### CODE REVIEW

**Comment by Kalmalyzer** [comment]
@ewanmellor Does this make sense for other users of UberLogger? Perhaps it would make more sense to make the ShowWindow property public?
(That way, people get enough flexibility so that they can query the current state, force a particular state, or toggle state, depending on their needs.)

**Comment by ewanmellor** [comment]
@Kalmalyzer Some people are sensitive about making properties public, so I went with this.  I don't mind either way though, exposing ShowWindow would be fine too.  I just want to toggle the window from my centralized input handler, I can do that in either case.  It's up to whoever's going to accept the change.

**Comment by Kalmalyzer** [comment]
@bbbscarter judgment call plz?

**Comment by bbbscarter** [comment]
Hi! Sorry for the delay.

Yup, my preference would be to turn ShowWindow into a property (probably just an auto-property for now) and make it public, and allow users to do whatever they want with it.

**Comment by ewanmellor** [comment]
Closed in favor of PR #49.

**Pull request closed without merging**
